### ISSUE TITLE
cargo pgrx test still fails after #28: #[pg_test] attribute macro unresolvable in cdylib test build (E0433)

### ISSUE THREAD

**Issue by evoludigit** [fraiseql/pg_tviews#29]
## Summary

After the fix in #28 (removing the spurious `use pgrx_tests::pg_test` import), `cargo pgrx test pg18` still fails to compile. The `#[pg_test]` attribute macro cannot be resolved in the crate root when building the cdylib for the pgrx test runner.

## Reproduction

```bash
cargo pgrx test pg18
```

## Error

```
error[E0433]: failed to resolve: could not find `pg_test` in the crate root
   --> src/lib.rs:798:5
    |
798 |     #[pg_test]
    |     ^^^^^^^^^^ could not find `pg_test` in the crate root
    |
    = note: this error originates in the attribute macro `pg_test`
```

Same error across all test functions in all 9 files that declare `#[pg_test]`-annotated functions.

## Environment

- pgrx / cargo-pgrx: `0.16.1`
- PostgreSQL: `18.1`
- Rust: `nightly-x86_64-unknown-linux-gnu (1.95.0-nightly)`
- pg_tviews: `0.1.0-beta.5`

## Root Cause Analysis

The `#[pg_test]` proc macro attribute is defined in `pgrx-macros` and re-exported via `pgrx` (`pub use pgrx_macros::*`). The test modules bring it into scope with:

```rust
#[cfg(feature = "pg_test")]
use pgrx::prelude::*;
```

However, `cargo pgrx test` builds the extension as a `cdylib` with `--features "pg18 pg_test" --no-default-features`. Proc macro attributes from external crates need to be in scope at the point of use. The issue is that `use pgrx::prelude::*` is itself gated behind `#[cfg(feature = "pg_test")]`, and even with the feature active the compiler reports it cannot find `pg_test` in the crate root when expanding `#[pg_test]`.

The standard pgrx pattern (as seen in the pgrx own examples and `cargo pgrx new`-generated projects) uses `#[cfg(any(test, feature = "pg_test"))]` on the module and unconditional `use pgrx::prelude::*` inside it, rather than gating the `use` statement behind the feature flag.

## Suggested Fix

In all test modules, change from:

```rust
#[cfg(feature = "pg_test")]
#[pg_schema]
mod tests {
    #[cfg(feature = "pg_test")]
    use pgrx::prelude::*;
    // ...
    #[cfg(feature = "pg_test")]
    #[pg_test]
    fn test_something() { ... }
}
```

To the standard pgrx pattern:

```rust
#[cfg(any(test, feature = "pg_test"))]
#[pg_schema]
mod tests {
    use pgrx::prelude::*;
    // ...
    #[pg_test]
    fn test_something() { ... }
}
```

This ensures `use pgrx::prelude::*` (and thus the `#[pg_test]` attribute macro) is unconditionally in scope within the module whenever the module is compiled, matching the pattern `cargo pgrx new` generates.

## Note

The current CI workflow works around both this issue and #28 by only running `cargo build --release` and relying on SQL integration tests in `test/sql/`. This issue would affect any contributor attempting to run `cargo pgrx test` locally.
